optimizer:
  class_name: "Adam"
  params:

   lr: 1e-4
scheduler:
  class_name: "LinearWarmupCosineAnnealingLR"
  params:
    warmup_epochs: 20
    max_epochs: ${trainer.params.max_epochs}
    warmup_start_lr: 5e-7
    eta_min: 1e-7
id: lr${optim.optimizer.lr}_warmupCosine${optim.scheduler.params.max_epochs}
# scheduler:
#   class_name: "MultiStepLR"
#   params:
#     gamma: 0.5
#     milestones:
#     - 10
#     - 50
#     - 150
# id: lr${optim.optimizer.lr}_Multstp${optim.scheduler.params.gamma}